# Generated by Django 2.2.5 on 2019-09-23 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190913_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userayah',
            options={'ordering': ('updated_at',)},
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayahs', models.ManyToManyField(to='profiles.UserAyah')),
                ('surahs', models.ManyToManyField(to='profiles.UserSurah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
