# Generated by Django 2.2.5 on 2019-09-29 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190923_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
