# Generated by Django 2.2.3 on 2019-07-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0002_auto_20190713_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
    ]
