# Generated by Django 2.2.1 on 2019-05-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text_madani', models.CharField(max_length=2048)),
                ('text_simple', models.CharField(max_length=2048)),
                ('sajdah', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English')], default='EN', max_length=32)),
                ('translation_type', models.CharField(choices=[('transliteration', 'Transliteration')], default='transliteration', max_length=32)),
                ('text', models.CharField(max_length=2048)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Ayah')),
            ],
        ),
        migrations.CreateModel(
            name='AyahWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_madani', models.CharField(max_length=64, null=True)),
                ('text_simple', models.CharField(max_length=64, null=True)),
                ('class_name', models.CharField(default='p1', max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('char_type', models.CharField(default='word', max_length=32)),
                ('number', models.IntegerField(default=0)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Ayah')),
            ],
        ),
        migrations.AddField(
            model_name='ayah',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Surah'),
        ),
    ]
