# Generated by Django 2.2.3 on 2019-07-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_number', models.IntegerField(default=0)),
                ('start_ayah', models.IntegerField(default=0)),
                ('end_ayah', models.IntegerField(default=0)),
                ('start_surah', models.IntegerField(default=0)),
                ('end_surah', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ayah',
            name='juz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surah',
            name='juz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ayah',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.Surah'),
        ),
        migrations.AlterField(
            model_name='ayahword',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.Ayah'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.Ayah'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='resource_name',
            field=models.CharField(choices=[('transliteration', 'Transliteration'), ('itani', 'Itani')], default='transliteration', max_length=32),
        ),
    ]
