# Generated by Django 2.2.5 on 2019-09-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20190724_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='resource_name',
            field=models.CharField(choices=[('transliteration', 'Transliteration'), ('itani', 'Itani'), ('shakir', 'Shakir')], default='transliteration', max_length=32),
        ),
    ]
