# Generated by Django 2.2.4 on 2019-10-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_auto_20190815_0616'),
        ('quran', '0003_auto_20190913_0102'),
    ]

    operations = [
    ]
